import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/nav/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-learning with AI",
  description: "E-learning content generated by AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
